Core/BlogCore/BlogCore/Areas/Admin/Controllers/CategoriesController.cs
using BlogCore.Data.Data.Repository;
using BlogCore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            // method to load page with the create form
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            // method to create cateogry
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Category currentCategory = _unitOfWork.Category.Get(id);
            if (currentCategory == null)
            {
                return NotFound();
            }
            return View(currentCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            // method to update cateogry
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.UpdateCategory(category);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }
        #region Consume Api


        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.Category.GetAll() });
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var categoryToDelete = _unitOfWork.Category.Get(id);
            if (categoryToDelete == null)
            {
                return Json(new { success = false, message = "An error occurred to delete category" });
            }
            _unitOfWork.Category.Remove(categoryToDelete);
            _unitOfWork.Save();
            return Json(new { success = true, message = string.Concat("Category ", categoryToDelete.Name, " was deleted") });
        }

        #endregion
    }
}

Core/BlogCore/BlogCore/Areas/Admin/Controllers/ItemsController.cs
using BlogCore.Data.Data.Repository;
using BlogCore.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;


namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ItemsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnviroment;
        public ItemsController(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnviroment)
        {
            _unitOfWork = unitOfWork;
            _hostingEnviroment = hostingEnviroment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            ItemVM item = new ItemVM()
            {
                Item = new Models.Item(),
                lstCategories = _unitOfWork.Category.GetListCategory()
            };
            return View(item);
        }

        [HttpPost]
        public IActionResult Create(ItemVM newItem)
        {
            if (ModelState.IsValid)
            {
                string path = _hostingEnviroment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                if (newItem.Item.Id == 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var upload = Path.Combine(path, @"img/items");
                    var extension = Path.GetExtension(files[0].FileName);
                    using (var fileStreams = new FileStream(Path.Combine(upload, string.Concat(fileName, extension)), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }
                    newItem.Item.UrlImage = string.Concat(@"/img/items/", fileName, extension);
                    newItem.Item.Creation = DateTime.Now;
                    _unitOfWork.Item.Add(newItem.Item);
                    _unitOfWork.Save();

                    return RedirectToAction(nameof(Index));
                }
            }
            newItem.lstCategories = _unitOfWork.Category.GetListCategory();
            return View(newItem);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            ItemVM item = new ItemVM()
            {
                Item = new Models.Item(),
                lstCategories = _unitOfWork.Category.GetListCategory()
            };
            if (id != null)
            {
                item.Item = _unitOfWork.Item.Get(id.GetValueOrDefault());
            }
            return View(item);
        }

        [HttpPost]
        public IActionResult Edit(ItemVM changeItem)
        {
            if (ModelState.IsValid)
            {
                string sourcePath = _hostingEnviroment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                var currentItem = _unitOfWork.Item.Get(changeItem.Item.Id);

                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var upload = Path.Combine(sourcePath, @"img/items");
                    var newExtension = Path.GetExtension(files[0].FileName);

                    var pathImage = Path.Combine(sourcePath, currentItem.UrlImage.TrimStart('/'));
                    if (System.IO.File.Exists(pathImage))
                    {
                        System.IO.File.Delete(pathImage);
                    }
                    using (var fileStreams = new FileStream(Path.Combine(upload, string.Concat(fileName, newExtension)), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }
                    changeItem.Item.UrlImage = string.Concat(@"/img/items/", fileName, newExtension);
                    changeItem.Item.Creation = DateTime.Now;
                }
                else
                {
                    changeItem.Item.UrlImage = currentItem.UrlImage;
                }
                _unitOfWork.Item.UpdateItem(changeItem.Item);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var eraserItem = _unitOfWork.Item.Get(id);
            string sourcePath = _hostingEnviroment.WebRootPath;
            var pathImg = Path.Combine(sourcePath, eraserItem.UrlImage.TrimStart('/'));

            if (System.IO.File.Exists(pathImg))
            {
                System.IO.File.Delete(pathImg);
            }
            if (eraserItem == null)
            {
                return Json(new { success = false, message = "An error happened during deleting process" });
            }

            _unitOfWork.Item.Remove(eraserItem);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Item deleted" });
        }
        #region Consume Api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.Item.GetAll(includeProperties: "Category") });
        }
        #endregion
    }
}

Core/BlogCore/BlogCore/Areas/Admin/Controllers/SlidersController.cs
using BlogCore.Data.Data.Repository;
using BlogCore.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BlogCore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SlidersController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostingEnviroment;

        public SlidersController(IUnitOfWork unitOfWork, IWebHostEnvironment hostingEnviroment)
        {
            _unitOfWork = unitOfWork;
            _hostingEnviroment = hostingEnviroment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            Slider newSlider = new Slider()
            {
                Name = "",
                UrlImage = ""
            };
            return View(newSlider);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Slider newSlider)
        {
            if (ModelState.IsValid)
            {
                string path = _hostingEnviroment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                string fileName = Guid.NewGuid().ToString();
                var upload = Path.Combine(path, @"img/items");
                if (files.Count == 0)
                {
                    newSlider.UrlImage = "Select an image";
                    return View(newSlider);
                }
                var extension = Path.GetExtension(files[0].FileName);
                using (var fileStreams = new FileStream(Path.Combine(upload, string.Concat(fileName, extension)), FileMode.Create))
                {
                    files[0].CopyTo(fileStreams);
                }
                newSlider.UrlImage = string.Concat(@"/img/items/", fileName, extension);

                _unitOfWork.Slider.Add(newSlider);
                _unitOfWork.Save();

                return RedirectToAction(nameof(Index));
            }
            return View(newSlider);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id != null)
            {
                var slider = _unitOfWork.Slider.Get(id.GetValueOrDefault());
                return View(slider);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Slider updateSlider)
        {
            if (ModelState.IsValid)
            {
                string sourcePath = _hostingEnviroment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                var currentSlider = _unitOfWork.Slider.Get(updateSlider.Id);

                if (files.Count > 0)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var upload = Path.Combine(sourcePath, @"img/slider");
                    var extension = Path.GetExtension(files[0].FileName);

                    var pathImage = Path.Combine(sourcePath, currentSlider.UrlImage.TrimStart('/'));
                    if (System.IO.File.Exists(pathImage))
                    {
                        System.IO.File.Delete(pathImage);
                    }
                    using (var fileStreams = new FileStream(Path.Combine(upload, string.Concat(fileName, extension)), FileMode.Create))
                    {
                        files[0].CopyTo(fileStreams);
                    }
                    updateSlider.UrlImage = string.Concat(@"/img/slider/", fileName, extension);

                }
                else
                {
                    updateSlider.UrlImage = currentSlider.UrlImage;
                }
                _unitOfWork.Slider.UpdateSlider(updateSlider);
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var eraserSlider = _unitOfWork.Slider.Get(id);
            if (eraserSlider == null)
            {
                return Json(new { success = false, message = "An error happened delete the slider" });
            }
            _unitOfWork.Slider.Remove(eraserSlider);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Slider deleted" });
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            return Json(new { data = _unitOfWork.Slider.GetAll() });
        }
    }
}

Core/BlogCore/BlogCore/Views/Shared/ViewCreateReturnPartial.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary" style="width:100%"> Create</button>
        &nbsp;
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success" style="width:100%"> Return</a>
    </div>
</div>

Core/BlogCore/BlogCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogCore</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!--Css todos-->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Client" asp-controller="Home" asp-action="Index">Blog_Core</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle text-white" id="nvddt" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Body
                            </a>
                            <div class="dropdown-menu" aria-labelledby="nvddt">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Categories" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Items" asp-action="Index">Item</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Sliders</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
                            </div>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>

    </header>
    <br />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BlogCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!--Js plugins-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/0f48d8c00d.js" crossorigin="anonymous"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>